baseURL = "http://stopbrexit.party/"
languageCode = "en-us"
title = "Stop Brexit Party"
theme = "detox"
publishDir = "docs"
[blackfriday]
  skipHTML=false
[params]
  author = "Kevin Marks"
  description = "Prevent a crash-out no deal Brexit by changing the default"
  twitter_name = "StopBrexitPart1"
